### ISSUE TITLE
how to read a xlsx data sheet?

### ISSUE THREAD

**Issue by ekosso** [mfbliposome/opentrons#2]
1. Opentrons cans read and runs the data sheet on the simulator
2. Not a library issue ( We loaded pandas on Hao computer and the Rasberry  pi without problem)
3. We can't use PowerShell because of administrator  doesn't allow us.
4. The site : "https://support.opentrons.com/s/article/Using-CSV-input-data-in-Python-protocols" will be helpful because it has the clue to solve this issue.
 May be we  can  run the protocol directly on the Rasberry pi without using the  Opentrons software on the desktop.

**Comment by jschrier** [comment]
It looks like the [preferred usage pattern is to create python input files that contain the data within them for each experiment](https://support.opentrons.com/s/article/Using-CSV-input-data-in-Python-protocols) (as per @ekosso 's #4 above)

The [opentrons protocol library](https://protocol-delivery.protocols.opentrons.com/protocol/1483-aurora-diagnostics) provides an example of how one might do this:
* Create a simple web-app that takes a CSV or XLSX file as input
* Web-app reads the input file and extracts the relevant columns
* Web-app emits a new python file that has the data (as defined variables) and the code (just copying the boilerplate run/setup code in the simplest case  or doing string replacements)

Of course, this need not be a web-app...it could just be a script

From the user's perspective in the lab, the workflow would look like:
1. Create the XLSX file (in the appropriate GitHub synchronized experimental results folder...) 
2. Upload the XLSX file to the web-app and download the resulting output python file (which also gets put into the appropriate GitHub synchronized experimental results folder...)
3. Load the output python file into the OpenTrons application and proceed 

Thoughts?

**Comment by ewroginek** [comment]
I was thinking something similar. If the OpenTrons application needs the data to be embedded in the input file, then I think the easiest thing to do is to create a python script that takes the xlsx data as input and creates another python file as output. That new file would then be uploaded via the OpenTrons GUI.

**Comment by ekosso** [comment]
I will try and let you know.

**Comment by ewroginek** [comment]
I wrote a new file called "generate_instructions.py". Given a filepath to an xlsx spreadsheet, it creates a new input file called "opentron_input.py". This file contains a string called "data" that is the information pulled from the xlsx spreadsheet, following the usage pattern in the links @ekosso and @jschrier included above. The code should now be readable by OpenTrons.

I didn't test this in the simulator due to some trouble setting the simulator up on my local machine. Maybe @hliu56 can try to see if it works?

PS - I had to edit the column headers in "opentron_input.py" from "None, Reagent 1, Reagent 2" to "Well, A1, A2" to fit the design pattern that Opentron needs.

**Comment by hliu56** [comment]
Thanks for generating the .py results Eric! @ewroginek 
Yes, I've  run the 'opentron_input.py' successfully by fixing a couple of bugs:
1. add 'import pandas as pd', since in the code it will use pd
2. change 'Well' to 'Well_number' (just a typo)
3. I try to iterate the values in each column, because the CSV_DATA[STOCK] is a pandas Series object, and in opentron it can't directly convert a Series to a single float.

I include the modified code and these running results in a new folder: 'hao_test', please have a look.

Maybe Eric and I can continue on the 'movement' part. Right now I use transfer operations and haven't thought that part too much yet....

**Comment by ekosso** [comment]
Hey guys, We will run the protocol tomorrow and let you know.
Thanks.

**Comment by ewroginek** [comment]
The code has been updated so that running `python main.py` will combine OT-2 instructions from a .xlsx data file and a preprocessed protocol file into a single post-processed protocol file that can be read by the OT-2 robot. The added functionality solves this issue
